### ISSUE TITLE
Get to 100% code coverage

### ISSUE THREAD

**Issue by dhermes** [google/oauth2client#212]
- [x] `oauth2client.client`
- [x] `oauth2client.contrib.appengine`
- [x] `oauth2client.contrib.django_orm`
- [x] `oauth2client.contrib.django_util.apps`
- [x] `oauth2client.contrib.locked_file`
- [x] `oauth2client.contrib.multistore_file`
- [x] `oauth2client.tools`
- [x] `oauth2client.util`
- [x] `tests.contrib.test_multistore_file` (#431, 3 branches: [1][2], [2][3], [3][4])
- [x] `tests.test_client` (#431, See [summary][1])
- [x] `tests.test_file` (#431, See [summary][1])

----

- [x] `oauth2client.__init__`
- [x] `oauth2client._helpers`
- [x] `oauth2client._openssl_crypt`
- [x] `oauth2client._pycrypto_crypt`
- [x] `oauth2client.clientsecrets` (PR: #278)
- [x] `oauth2client.contrib.__init__`
- [x] `oauth2client.contrib.django_util.__init__`
- [x] `oauth2client.contrib.django_util.decorators`
- [x] `oauth2client.contrib.django_util.signals`
- [x] `oauth2client.contrib.django_util.site`
- [x] `oauth2client.contrib.django_util.storage`
- [x] `oauth2client.contrib.django_util.views`
- [x] `oauth2client.contrib.flask_util` (Issue: #277, PR: #282)
- [x] `oauth2client.contrib.keyring_storage` (PR: #279)
- [x] `oauth2client.crypt` (PR: #290)
- [x] `oauth2client.devshell` (PR: #284)
- [x] `oauth2client.file`
- [x] `oauth2client.gce` (PR: #280)
- [x] ~~`oauth2client.old_run` (PR: #285)~~ yay it's gone
- [x] `oauth2client.service_account`
- [x] `oauth2client.xsrfutil` (PR: #281)
- [x] `tests.__init__`
- [x] `tests.contrib.__init__`
- [x] `tests.contrib.test_appengine` (See [summary][1])
- [x] `tests.contrib.test_django_orm`
- [x] `tests.contrib.test_django_settings`
- [x] `tests.contrib.test_django_util`
- [x] `tests.contrib.test_flask_util`
- [x] `tests.contrib.test_keyring_storage`
- [x] `tests.http_mock` (See [summary][1])
- [x] `tests.test__helpers`
- [x] `tests.test__pycrypto_crypt`
- [x] `tests.test_clientsecrets` (See [summary][1])
- [x] `tests.test_crypt`
- [x] `tests.test_devshell` (See [summary][1])
- [x] `tests.test_gce`
- [x] `tests.test_jwt` (See [summary][1])
- [x] `tests.test_service_account` (See [summary][1])
- [x] `tests.test_tools` (See [summary][1])
- [x] `tests.test_util`
- [x] `tests.test_xsrfutil` (See [summary][1])

[1]: https://github.com/google/oauth2client/pull/297#issuecomment-142150899
[2]: https://github.com/google/oauth2client/blob/682baf0d727156c5c0bf8029ad7eabb66d367958/tests/contrib/test_multistore_file.py#L107-L109
[3]: https://github.com/google/oauth2client/blob/682baf0d727156c5c0bf8029ad7eabb66d367958/tests/contrib/test_multistore_file.py#L112-L125
[4]: https://github.com/google/oauth2client/blob/682baf0d727156c5c0bf8029ad7eabb66d367958/tests/contrib/test_multistore_file.py#L157-L159

**Comment by dhermes** [comment]
This will "fix" #209 among other things.

Overall, test status of this library is quite bad and the uber-module `client.py` and it's uber-test-module `test_oauth2client.py` could benefit from being split apart.

**Comment by dhermes** [comment]
First order of business, separate out import madness from `crypt.py` and put `OpenSSL` and `pyCrypto` implementations in separate modules.

**Comment by dhermes** [comment]
As of right now (59e59a676734dcbaeb62b78dda1d9409cfabfc99, after #276 merged), here is the output of `tox -e cover`

```
Name                           Stmts   Miss Branch BrMiss  Cover   Missing
--------------------------------------------------------------------------
oauth2client                       7      0      0      0   100%   
oauth2client._helpers             27      0      6      0   100%   
oauth2client._openssl_crypt       41      0      4      0   100%   
oauth2client._pycrypto_crypt      40      0      4      0   100%   
oauth2client.client              725     84    207     45    86%   57-58, 164, 206, 215, 224, 232, 292-296, 355, 365, 372, 724, 741, 776, 889, 892-894, 931-932, 1221, 1237, 1258, 1345, 1418-1422, 1489-1491, 1495-1497, 1551, 1572, 1701, 1875-1896, 1999-2004, 2007, 2017, 2029-2067, 2093, 2095, 2098, 2113, 2163, 2222, 2227-2233
oauth2client.clientsecrets        51      1     20      2    96%   78
oauth2client.crypt                87     14     28      6    83%   44-49, 54-56, 62-66, 153, 167
oauth2client.devshell             53      3      8      2    92%   60, 85, 132
oauth2client.django_orm           68     26     22     14    56%   46, 48, 53, 71, 73, 78, 101-104, 112-120, 131-140, 145-146
oauth2client.file                 47      0      4      0   100%   
oauth2client.flask_util          170      9     42      7    92%   180-181, 383-384, 387, 394-397
oauth2client.gce                  39      3      4      1    91%   92-93, 97
oauth2client.keyring_storage      29      1      2      0    97%   114
oauth2client.locked_file         183    101     64     47    40%   91, 100, 104, 124-158, 162-169, 173, 196, 216-230, 239-240, 245-329, 351, 356
oauth2client.multistore_file     165     17     24      7    87%   287-294, 360-363, 368-369, 372, 379-380, 386-388, 466-467
oauth2client.service_account      54      0      0      0   100%   
oauth2client.tools               109     65     18     16    36%   54-55, 165-239, 244, 249, 252
oauth2client.util                 55     18     18     10    62%   129-141, 148-149, 219-226
oauth2client.xsrfutil             48      3     14      3    90%   42, 100, 109
--------------------------------------------------------------------------
TOTAL                           1998    345    489    160    80%   
----------------------------------------------------------------------
Ran 222 tests in 8.526s
```

I haven't yet figured out how to build in `oauth2client/appengine.py` but will do so soon-ish.

**Comment by dhermes** [comment]
@jonparrott You previously mentioned that it was possible to collect coverage from multiple runs. I am looking to do this for `oauth2client.appengine`.

Care to help? Shall I file a bug and we take it up there / have a PR which closes that bug?

**Comment by jonparrott** [comment]
Yep, file a bug. I'll see what I can do.

**Comment by dhermes** [comment]
As per discussion with @nathanielmanistaatgoogle in #288, need to be sure to:

- Take a look at `test_jwt.py` and see if it should be split up (#211 may force this one)
- Add direct tests for `_openssl_crypt.py` rather than relying on `test_jwt.py` to indirectly test it (you may disagree with me on this)

**Comment by dhermes** [comment]
After doing #293 I wanted to make sure I hadn't reduced the coverage of `client.py`, so actually went through all the lines missing coverage

```
57-58  # PRAGMA
169  'def _abstract', easy to test
211, 220, 229, 237 -- all abstract methods
297-301 -- import error for old code
360, 370, 377 -- all abstract methods
729 -- branch in method
746 -- branch (default arg)
781 -- branch in method
894 -- error_description in payload (branch)
897 -- store is not None (branch)
898-899 -- exception occurs
936-937 -- error in payload (branch)
1222 -- fall-through to GAE environ for ADC
1238 -- fall-through to GCE environ for ADC
1259 -- fall-through to well-known file for ADC
1346 -- from_stream failure
1419-1423 -- windows keyerror in _get_well_known_file()
1490-1492 -- _get_application_default_credential_GAE() method (untested)
1496-1498 -- _get_application_default_credential_GCE() method (untested)
1552 -- abstract method
1573 -- _RequireCryptoOrDie() failure
1702 -- verify_id_token default input for http
1876-1897 -- DeviceFlowInfo.FromResponse (entire method)
2000-2005 -- branch for non-None value (a log statement and a setter)
2008 -- exception if None value encountered
2018 -- login_hint is set (branch)
2030-2068 -- OAuth2WebServerFlow.step1_get_device_and_user_codes (entire method)
2094 -- branch (two null inputs, need exactly one to be non-null)
2096 -- branch (same as 2096, but two non-null inputs)
2099 -- branch (code input var is None)
2114 -- branch (device_flow_info input var is None)
2223 -- branch (device_uri input var is None)
2228-2234 -- exceptions at end of method
```

Many of them are abstract methods that are easy to test (i.e. `self.assertRaises(NotImplementedError, ...)`) and be on your merry way.

**Comment by dhermes** [comment]
@waprin I just updated the list after #332 got in and noticed `oauth2client.contrib.django_util.apps` slipped in.

IIRC we discussed during that PR that you might knock off coverage for `django_orm` as well.

Still down to help got to 100% coverage?

**Comment by waprin** [comment]
Yes sure. I thinks the apps.py can be tested since we're no longer running Django tests for 2.6 I will either cover django_orm or just rewrite as my next task.

**Comment by dhermes** [comment]
:+1: on the rewrite

**Comment by dhermes** [comment]
Might want to work upstream from #353 to avoid merge headaches

**Comment by dhermes** [comment]
@waprin We had previously discussed you getting `django_orm.py` both 100% covered and maybe even making the code better? Are you still up for that?

**Comment by waprin** [comment]
I believe apps is not covered because it's only part of later versions of Django that don't support 2.6. Now given coverage runs under Python 2.7 I forget the specific reason for why it's not covered but it was something along those lines, I'd have to revisit.

**Comment by dhermes** [comment]
`tox -e cover` only runs with 2.7.

**Comment by waprin** [comment]
Well there is a pragma nocover in there so it's basically 0% of 0 (well, except for not testing `import sys`).  I think I just needed a Python 2.7+ only test-case, since it's basically a metadata class it didn't seem super-important to test but I'll take another look at it.

**Comment by dhermes** [comment]
I consider this a successful week!
